name: GitHub Actions
run-name: Running Fuzz Test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: python fuzz.py
